version: '2'
services:
  openldap:
    restart: always
    image: hrektts/fusiondirectory-openldap:latest
    environment:
      - LDAP_ORGANISATION="Example Organization"
      - LDAP_DOMAIN=example.com
      - LDAP_ADMIN_PASSWORD=adminpwd
      - LDAP_CONFIG_PASSWORD=configpwd
      - LDAP_ADMIN_DN="cn=admin,dc=example,dc=com" 

      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=reader
      - LDAP_READONLY_USER_PASSWORD=readerpwd

      - FD_ADMIN_PASSWORD=fdadminpwd

  fusiondirectory:
    restart: always
    image: aledemelo/docker-fusiondirectory:latest
    ports:
      - "10080:80"
    depends_on:
      - openldap
    environment:
      - LDAP_DOMAIN=example.com
      - LDAP_HOST=openldap
      - LDAP_ADMIN_PASSWORD=adminpwd 
